[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/docker/cli"
  version = "v18.06.0-ce"

[[constraint]]
  name = "github.com/docker/distribution"
  branch = "master"

[[constraint]]
  name = "github.com/Azure/azure-sdk-for-go"
  version = "v14.0.0"

[[constraint]]
  name = "github.com/Azure/go-autorest"
  version = "v10.1.0"

[[constraint]]
  name = "github.com/Masterminds/sprig"
  version = "2.16.0"

[[constraint]]
  name = "github.com/gobuffalo/packr"
  version = "2.0.0-rc.8"

[[constraint]]
  name = "github.com/kelseyhightower/envconfig"
  version = "1.3.0"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true
