[[override]]
  name = "github.com/deislabs/cnab-go"
  # version = "v0.7.1-beta1"
  source = "github.com/radu-matei/cnab-go"
  branch = "deps"

[[override]]
  name = "github.com/docker/cnab-to-oci"
  version = "v0.3.0-beta1"

[[constraint]]
  name = "github.com/carolynvs/datetime-printer"
  version = "v0.2.0"

#
# SEMVER IS DEAD, LONG LIVE SEMVER
# Use a very specific version of docker and its libraries because they aren't contained in a release yet, but cnab-go references some unreleased feature/code ¯\_(ツ)_/¯
#
[[override]]
  name = "github.com/containerd/containerd"
  version = "v1.3.0"

[[override]]
  name = "github.com/docker/distribution"
  #version = "v2.7.1"
  revision = "0d3efadf0154c2b8a4e7b6621fff9809655cc580"

[[override]]
  name = "github.com/docker/docker-credential-helpers"
  version = "v0.6.3"

[[override]]
  name = "golang.org/x/sys"
  revision = "f49334f85ddcf0f08d7fb6dd7363e9e6d6b777eb"

[[override]]
  name = "github.com/google/go-containerregistry"
  revision = "ef12d49c8daf6a6d72978966d5945e39bb898b4a"

[[override]]
  name = "github.com/Microsoft/hcsshim"
  revision = "2226e083fc390003ae5aa8325c3c92789afa0e7a"

#
# End Pinning
#

# Use v2 of packr, not master
[[constraint]]
  name = "github.com/gobuffalo/packr"
  version = "v2"

# Use v1.1+ of jsonschema
[[constraint]]
  name = "github.com/xeipuuv/gojsonschema"
  version = "v1.1.0"

# We are using this because it unmarshals yaml to map[string]interface{} which
# works better with json schema validation.
[[constraint]]
  name = "github.com/ghodss/yaml"
  version = "v1.0.0"

# See https://github.com/shurcooL/github_flavored_markdown/issues/12
[[override]]
  name = "github.com/russross/blackfriday"
  branch = "master"

[[constraint]]
  name = "github.com/PaesslerAG/jsonpath"
  version = "v0.1.1"

[[constraint]]
  name = "github.com/hashicorp/go-plugin"
  #version = "^v1.0.0"
  source = "github.com/carolynvs/go-plugin"
  branch = "accept-stdin"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true

# This is temporary until we know what packages we need from cnab-go
[[prune.project]]
  name = "github.com/deislabs/cnab-go"
  unused-packages = false

[[constraint]]
  name = "github.com/cbroglie/mustache"
  version = "1.0.1"
