baseURL = "/"
languageCode = "en-us"
title = "Porter"
theme = "porter"

# Docs Navigation

[params]
  title = "Porter"
  author = "Carolyn Van Slyck"
  description = "Porter - A Friendlier Cloud Installer"

canonifyURLs = "false"
relativeURLs = "true"
pluralizeListTitles = "false"
plainIdAnchors = "true"
defaultContentLanguage = "en"

[[menu.main]]
  name = "Getting Started"
  url = "/getting-started"
  identifier = "getting-started"
  weight = 2
  [[menu.main]]
    name = "Install Porter"
    url = "/install"
    identifier = "install"
    weight = 11
    parent = "getting-started"
  [[menu.main]]
    name = "QuickStart"
    url = "/quickstart"
    identifier = "quickstart"
    weight = 12
    parent = "getting-started"
  #[[menu.main]]
  #  name = "Finding Bundles"
  #  url = "/finding-bundles"
  #  identifier = "finding-bundles"
  #  weight = 16
  #  parent = "getting-started"

[[menu.main]]
  name = "Porter Commands"
  url = "/cli"
  identifier = "cli"
  weight = 102
  [[menu.main]]
    name = "porter create"
    url = "/cli#create"
    identifier = "cli-create"
    weight = 123
    parent = "cli"
  [[menu.main]]
    name = "porter build"
    url = "/cli#build"
    identifier = "cli-build"
    weight = 124
    parent = "cli"
  [[menu.main]]
    name = "porter run"
    url = "/cli#run"
    identifier = "cli-run"
    weight = 125
    parent = "cli"
  [[menu.main]]
    name = "porter list mixins"
    url = "/cli#list-mixins"
    identifier = "cli-list-mixins"
    weight = 126
    parent = "cli"
  [[menu.main]]
    name = "porter completion"
    url = "/cli#completion"
    identifier = "cli-completion"
    weight = 198
    parent = "cli"
  [[menu.main]]
    name = "porter version"
    url = "/cli#version"
    identifier = "cli-version"
    weight = 199
    parent = "cli"

[[menu.main]]
  name = "Authoring Bundles"
  identifier = "authoring-bundles"
  weight = 200
  [[menu.main]]
    name = "Overview"
    url = "/authoring-bundles"
    identifier = "authoring-bundles-overview"
    weight = 201
    parent = "authoring-bundles"
  [[menu.main]]
    name = "Using Mixins"
    url = "/using-mixins"
    identifier = "using-mixins"
    weight = 202
    parent = "authoring-bundles"
  [[menu.main]]
    name = "Dependencies"
    url = "/dependencies"
    identifier = "dependencies"
    weight = 203
    parent = "authoring-bundles"
  [[menu.main]]
    name = "Using Parameters, Credentials and Outputs"
    url = "/wiring"
    identifier = "wiring"
    weight = 203
    parent = "authoring-bundles"
  #[[menu.main]]
  #  name = "Signing Bundles"
  #  url = "/signed-bundles"
  #  identifier = "signed-bundles"
  #  weight = 206
  #  parent = "authoring-bundles"
  #[[menu.main]]
  #  name = "Distributing Bundles"
  #  url = "/distributing-bundles"
  #  identifier = "distributing-bundles"
  #  weight = 207
  #  parent = "authoring-bundles"

[[menu.main]]
  name = "Developing Mixins"
  identifier = "developing-mixins"
  weight = 300
  [[menu.main]]
    name = "Overview"
    url = "/mixin-dev-guide"
    identifier = "mixin-dev-guide"
    weight = 301
    parent = "developing-mixins"
  [[menu.main]]
    name = "Commands"
    url = "/mixin-commands"
    identifier = "mixin-commands"
    weight = 303
    parent = "developing-mixins"
  [[menu.main]]
    name = "Mixin Architecture"
    url = "/mixin-architecture"
    identifier = "mixin-architecture"
    weight = 310
    parent = "developing-mixins"
  #[[menu.main]]
  #  name = "Distributing Mixins"
  #  url = "/mixin-distribution"
  #  identifier = "mixin-distribution"
  #  weight = 311
  #  parent = "developing-mixins"

[[menu.main]]
  name = "Porter Architecture"
  identifier = "porter-architecture"
  weight = 400
  [[menu.main]]
    name = "Overview"
    url = "/architecture"
    identifier = "architecture"
    weight = 401
    parent = "porter-architecture"
  [[menu.main]]
    name = "Buildtime"
    url = "/architecture-buildtime"
    identifier = "architecture-buildtime"
    weight = 402
    parent = "porter-architecture"
  [[menu.main]]
    name = "Runtime"
    url = "/architecture-runtime"
    identifier = "architecture-runtime"
    weight = 403
    parent = "porter-architecture"
  [[menu.main]]
    name = "Invocation Images"
    url = "/build-image"
    identifier = "build-image"
    weight = 404
    parent = "porter-architecture"

[[menu.main]]
  name = "References"
  identifier = "references"
  weight = 600
  [[menu.main]]
    name = "CNAB Spec"
    url = "https://cnab.io"
    identifier = "cnab"
    weight = 600
    parent = "references"
