# This is the configuration for Porter
# You must define steps for each action, but the rest is optional
# Uncomment out the sections below to take full advantage of what Porter can do!

mixins:
  - exec

name: HELLO
version: 0.1.0
description: "An example Porter configuration"
invocationImage: porter-hello:latest

install:
  - exec:
      description: "Install Hello World"
      command: bash
      arguments:
        - -c
        - echo Hello World

uninstall:
  - exec:
      description: "Uninstall Hello World"
      command: bash
      arguments:
        - -c
        - echo Goodbye World

#dependencies:
#  - name: mysql
#    parameters:
#      database-name: wordpress

#credentials:
#  - name: kubeconfig
#    path: /root/.kube/config
